### ISSUE TITLE
AttributeError: module transformers has no attribute generation_beam

### ISSUE THREAD

**Issue by zellford** [amazon-science/faithful-summarization-generation#5]
Package            Version
------------------ ------------
aiohttp            3.8.4
aiosignal          1.3.1
async-timeout      4.0.2
attrs              23.1.0
certifi            2023.5.7
charset-normalizer 3.1.0
datasets           2.12.0
dill               0.3.6
filelock           3.12.0
frozenlist         1.3.3
fsspec             2023.5.0
huggingface-hub    0.14.1
idna               3.4
multidict          6.0.4
multiprocess       0.70.14
numpy              1.24.3
packaging          23.1
pandas             2.0.1
Pillow             9.5.0
pip                23.0.1
pyarrow            12.0.0
python-dateutil    2.8.2
pytz               2023.3
PyYAML             6.0
regex              2023.5.5
requests           2.30.0
responses          0.18.0
setuptools         66.0.0
six                1.16.0
tokenizers         0.13.3
torch              1.11.0+cu113
torchaudio         0.11.0+cu113
torchvision        0.12.0+cu113
tqdm               4.65.0
transformers       4.29.1
typing_extensions  4.5.0
tzdata             2023.3
urllib3            2.0.2
wheel              0.38.4
xxhash             3.2.0
yarl               1.9.2

When I try to run this:
faithful-summarization-generation# python lookahead/run_generate.py --document_file /root/datasets/xsum_fairseq/train.source --output_file xsum_greedy_lookahead_greedy.summary --do_lookahead --lookahead_decoding_type greed
y

Traceback (most recent call last):
  File "lookahead/run_generate.py", line 3, in <module>
    from lookahead import Lookahead
  File "/root/faithful-summarization-generation/lookahead/lookahead.py", line 14, in <module>
    from transformers.generation_beam_constraints import Constraint, DisjunctiveConstraint, PhrasalConstraint
ModuleNotFoundError: No module named 'transformers.generation_beam_constraints'

DO anyone know how to solve this problem?

**Comment by meetdavidwan** [comment]
Hi thanks for the interest!

Could you try transformers version 4.21.0? Looking at the latest transformers code, they seemed to have revamped the generation code, and my implementation (based on the 4.21.0 GenerationMixin) seems no longer valid.
